Fixed Travis build and testing

diff --git a/validate_plugin b/validate_plugin
--- a/validate_plugin
+++ b/validate_plugin
@@ -4,6 +4,26 @@
 
 set -e
 
+TARGET="$1"
+
+# Checks if the target passed in matches the first argument. If no argument is given, then all targets should run
+function should_run_target() {
+    name="$1"
+
+    if [[ "${TARGET}" -eq "${name}" || -z "${TARGET}" ]]; then
+        return 0
+    else
+        return 1
+    fi
+}
+
+function kill_emulator() {
+    pkill emulator || true
+    pkill emulator64-arm || true
+    pkill emulator64-x86|| true
+    rm -f ./example-android-project/build/android-avd-root/*/*.lock
+}
+
 # Clean up possibly existing files to ensure a fresh start
 rm -f 'example-android-project/local.properties'
 rm -rf 'example-android-project/build'
@@ -12,19 +32,33 @@ rm -rf 'android-emulator-plugin/build'
 # Plugin locally to be consumed by example project
 ./gradlew -p android-emulator-plugin publishToMavenLocal
 
-# Base
-./gradlew -p example-android-project connectedCheck
+# ADB install may take longer than normal in Travis due to the low-power machine
+export ADB_INSTALL_TIMEOUT=10
 
-# Use a new Gradle plugin and an older SDK version
-ANDROID_GRADLE_VERSION=3.2.1 ANDROID_GRADLE_VERSION_NEW=true ANDROID_EMULATOR_SDK_VERSION=21 ./gradlew -p example-android-project connectedCheck
+# Add additional gradle options for testing
+export GRADLE_OPTS="${GRADLE_OPTS} -Dorg.gradle.logging.level=info"
 
-# Change the SDK version, enable google_apis flavor, and a non-x86 abi
-ANDROID_EMULATOR_SDK_VERSION=15 ANDROID_EMULATOR_GOOGLE_APIS=true ANDROID_EMULATOR_ABI=armeabi-v7a ./gradlew -p example-android-project connectedCheck
+# Run the test on the default (for the project) emulator as well as using the new Gradle plugin with an older SDK version
+# Run one after the other to ensure the plugin handles changing of configuration.
+if should_run_target 1; then
+    ./gradlew -p example-android-project connectedCheck
+    kill_emulator
+    ANDROID_GRADLE_VERSION=3.2.1 ANDROID_GRADLE_VERSION_NEW=true ANDROID_EMULATOR_SDK_VERSION=21 ./gradlew -p example-android-project connectedCheck
+fi
 
-# Validate that the emulator is needed or the tests would fail
-ENABLE_FOR_ANDROID_TESTS=false ./gradlew -p example-android-project connectedCheck && \
-        echo 'Build should not have succeeded' && exit 1 || \
-        echo 'Build failure expected due to "No connected devices!"'
+# Use a google_apis flavor
+if should_run_target 2; then
+    ANDROID_EMULATOR_SDK_VERSION=24 ANDROID_EMULATOR_GOOGLE_APIS=true ./gradlew -p example-android-project connectedCheck
+fi
 
-# Use the old Gradle plugin with a newer sdk version
-ANDROID_GRADLE_VERSION=2.3.3 ANDROID_GRADLE_VERSION_NEW=false ANDROID_EMULATOR_SDK_VERSION=27 ./gradlew -p example-android-project connectedCheck
+# Validate that the emulator is needed or the tests would fail due to a lack of devices
+if should_run_target 3; then
+    ENABLE_FOR_ANDROID_TESTS=false ./gradlew -p example-android-project connectedCheck && \
+            echo 'Build should not have succeeded' && exit 1 || \
+            echo 'Build failure expected due to "No connected devices!"'
+fi
+
+# Use the old Gradle plugin
+if should_run_target 4; then
+    ANDROID_GRADLE_VERSION=2.3.3 ANDROID_GRADLE_VERSION_NEW=false ANDROID_EMULATOR_GOOGLE_APIS=true ANDROID_EMULATOR_SDK_VERSION=24 ./gradlew -p example-android-project connectedCheck
+fi
