Resolves #27: Abort waitForAndroidEmulator task when emulator process crashes

diff --git a/validate_plugin b/validate_plugin
--- a/validate_plugin
+++ b/validate_plugin
@@ -72,3 +72,11 @@ fi
 if should_run_target 6; then
     LOG_ANDROID_EMULATOR=true ANDROID_EMULATOR_SDK_VERSION=24 ANDROID_EMULATOR_GOOGLE_APIS=true ./gradlew -p example-android-project connectedCheck
 fi
+
+# Use the failed emulator starts don't hang forever
+if should_run_target 7; then
+    FAIL_EMULATOR_STARTUP=true ./gradlew -p example-android-project assemble # Prove the flag doesn't fail the build
+    FAIL_EMULATOR_STARTUP=true ./gradlew -p example-android-project connectedCheck && \
+            echo 'Build should not have succeeded' && exit 1 || \
+            echo 'Build failure expected due to invalid emulator arguments'
+fi
